"""Replace relationship with name in Beneficiary model

Revision ID: 2fdb841ce428
Revises: 0336a9b3f1a0
Create Date: 2024-11-20 08:29:59.663607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdb841ce428'
down_revision = '0336a9b3f1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
